apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: eksporter
spec:
  version: "v1.0.0"
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
        - windows
    uri: https://github.com/Kyrremann/kubeflow-eksporter/releases/download/v1.0.0/eksporter.tar.gz
    sha256: "1c13fac59c1c306db8498f394ee4cf1ba98eaa44c6f404fc2fad505533f00835"
    files:
    - from: "/eksporter.rb"
      to: "."
    bin: "./eksporter.rb"
  shortDescription: Export resources and removes a pre-defined set of fields for later import
  homepage: https://github.com/Kyrremann/kubeflow-eksporter
  caveats: |
    This plugin needs the following programs:
    * ruby
  description: |
    This plugin helps you export a resource, and removes a pre-defined set of
    fields. This is useful for when you have resource you want to migrate from
    one namespace or cluster, to another one, but need to edit/add some fields
    before applying.

    If you just need to move one resource, it's probably easier to just:
      kubectl get -oyaml | kubectl create -f -

    Run the tool with:
      kubectl eksporter <resource> <resource_name>
